### ISSUE TITLE
Add support for changing the ssh port

### ISSUE THREAD

**Issue by rbarlow** [jpwoodbu/ari-backup#11]
Right now I'm working around this by changing settings.ssh_path to /usr/bin/ssh -p <port>, but that's not nice :)

**Comment by jpwoodbu** [comment]
^ @rbarlow

**Comment by jpwoodbu** [comment]
@rbarlow, I was able to complete testing on this feature. It's now in the master branch in version 1.0.5. Enjoy!

**Comment by rbarlow** [comment]
On 01/11/2015 08:14 PM, jpwoodbu wrote:
> @rbarlow <https://github.com/rbarlow>, I was able to complete testing on
> this feature. It's now in the master branch in version 1.0.5. Enjoy!

Excellent, I look forward to upgrading!
