### ISSUE TITLE
PEP-8 ari-backup

### ISSUE THREAD

**Issue by bowlofeggs** [jpwoodbu/ari-backup#22]
I'd like to PEP-8 ari-backup, which would involve touching nearly every single line of code (PEP-8 suggests 4 space indentation everywhere, and a lot of ari-backup uses 2.) Any objections?

**Comment by jpwoodbu** [comment]
I actually can't remember (I should have written in the README) whether I tried to follow PEP-8 or the Google Python Style Guide. If I had to guess, probably the latter, but I don't know how they're different. At least when it comes to indentation, they seem to agree. I used a style where indentation levels used 2 spaces, but wrapped lines used 4. But I don't mind aligning the code to one of the aforementioned style guides. Do you know how they differ and/or have a preference?

My only request is that style change commits should include no other changes.

**Comment by rbarlow** [comment]
PEP-8 says to use 4 spaces per indentation level, and this is what the Python community has largely adopted:

https://www.python.org/dev/peps/pep-0008/#indentation

I'm not familiar with the Google style guide, but a significant advantage in going with the Python convention is that most editors are able to follow along better when PEP-8 is used, and there is a really great PEP-8 checker called flake8 (pip install flake8 and type flake8 . to run it on the code) that can be used to automatically enforce PEP-8 on pull requests with Travis.

**Comment by rbarlow** [comment]
One exception that I like to make to PEP-8 (and I think is also a common exception) is to allow lines longer than 79. I personally like to wrap at 100 columns, but it is arbitrary. I think 79 causes too many line wraps and in my opinion makes the code less readable as a result.

**Comment by jpwoodbu** [comment]
I would prefer to continue wrapping at 79 columns. I find having code of that width is nice when doing side by side diffs.

**Comment by bowlofeggs** [comment]
Cool, I'll go with 79 then.
