### ISSUE TITLE
Allow configurable exception table for LVM snapshots

### ISSUE THREAD

**Issue by robled** [jpwoodbu/ari-backup#27]
Right now this is hardcoded at 1G, and there's a TODO in the code to make this better.  I'm now running out of exception table space with 1G, so this is something that should be configurable via YAML.

**Comment by robled** [comment]
I don't think I have access to assign this ticket to myself, but I can take this on.

**Comment by scottlinux** [comment]
I'm hitting this issue currently.

It appears with LVM2 that this is perhaps not needed?

http://www.tldp.org/HOWTO/LVM-HOWTO/snapshotintro.html

**Comment by robled** [comment]
After reading those docs and looking at some examples I think that an exception table is still required for LVM2.  The current work-around for this issue in ari-backup is to change the value in _/usr/local/lib/python2.7/dist-packages/ari_backup/lvm.py_ line 105.

**Comment by jpwoodbu** [comment]
Commit 8464d7b010cd761c6ee924fa6758f3eb4a2a0aaf added `snapshot_size` has a config option.
