### ISSUE TITLE
Port ari-backup so that it works with Python 3.4+

### ISSUE THREAD

**Issue by bowlofeggs** [jpwoodbu/ari-backup#30]
There is an initiative in the Fedora project to convert all our Python packages to Python 3 (and to drop the ones that don't support Python 3 by some date that I don't know but probably isn't extremely soon):

http://fedora.portingdb.xyz/

In fact, you can even look at ari-backup in there to see how things are looking for us:

http://fedora.portingdb.xyz/pkg/ari-backup/

Now portingdb doesn't know something that we do know - that we actually only use rdiff-backup through subprocess and not by importing it. Probably we should consider importing it one day so we can use it more cleanly. Until that day, we can "cheat" a little by leaving things as they are and going ahead and porting ari-backup to support Python 3. Once rdiff supports Python 3 (and by the way, the upstream for rdiff recently changed hands and it is once again an active project), we can look at using their API directly.

This leaves me with an implementation detail question: do we want to continue to support Python 2.7? It is possible to support Python 3.something+ (I think it's 3.2+?) and Python 2.7 (but not 2.6 or less) at the same time, but it would be more work than just being purely Python 3. I'm personally happy being Python 3 only for my own systems that use ari-backup, but if we have a need to also support Python 2.7 perhaps the extra effort is worth it.

What do you think?

EDIT: During discussion, it was agreed that ari-backup can/will become Python 3.4+ only, dropping support for Python 2.

**Comment by jpwoodbu** [comment]
Looking at least at what versions of Debian have Python 3 support, only supporting Python 3 seems fine to me. In my 5s of searching I didn't see a nice list of which versions of Ubuntu support Python 3, but it's probably similar to the Debian story.

The only other big users of ari-backup that I know of are MetaMetrics. Scott might know best the impact of dropping Python 2.7 support for them.

**Comment by bowlofeggs** [comment]
@scottlinux, would you care to weigh in on whether ari-backup should continue to support Python 2.7 going forward, or whether going Python 3 only will suffice?

**Comment by scottlinux** [comment]
I'm good with Python 3.2+ and dumping 2.7.

MM is all on Debian jessie currently. The Python 3 version in jessie appears to be 3.4.2. Thanks,

**Comment by bowlofeggs** [comment]
Fantastic! This raises the next question of mine - can we require Python 3.4+, or do we want to try to support 3.2? All supported Fedora releases and EPEL 7 have 3.4 or higher, so 3.4+ works for me. The only real difference will be some features in the newer Pythons that might be nice to have available to us.

**Comment by jpwoodbu** [comment]
3.4+ works for me. Jessie has 3.4 and Wheezy, according to policy, is
probably not support anymore.

**Comment by bowlofeggs** [comment]
Excellent, I will update the title and body of this ticket.

**Comment by bowlofeggs** [comment]
Another thought I've had lately - what if we converted ari-backup to be a set of Ansible roles/playbooks? If we did that, we could let Ansible handle all the task execution (which is what a lot of the ari-backup code does) and probably greatly simplify the project. Honestly, maybe it'd be better to just start a whole new project if we went this route, but I think it could be nicer.

What do you all think?

**Comment by jpwoodbu** [comment]
I don't have any experience with Ansible so I don't have an opinion. If it's a high quality match, I have no objection to leaning on other components to do more of the heavy lifting.

**Comment by scottlinux** [comment]
Ansible has a zfs module:

https://docs.ansible.com/ansible/zfs_module.html

**Comment by jpwoodbu** [comment]
As of commit 0d988b0a2da5dd2c3b6b58a091cb187ee746866c, Python 3 is supported. The tests have passed on 3.11. I have not confirmed functionality beyond that.
