### ISSUE TITLE
unable to backup anything but entire root filesystem using ZFSLVMBackup

### ISSUE THREAD

**Issue by robled** [jpwoodbu/ari-backup#6]
With rdiff-backup it's possible to specify certain subdirectories and only back those up.  Additionally, rdiff-backup uses fancy include/exclude rules to build the top-level directories so that the backed-up subdirectories make sense in the context of the root filesystem.  This feature is great to have so that you know exactly where to restore data to.

Since ZFSLVMBackup uses rsync and rsync doesn't have fancy include/exclude rules, we can currently only back up the entire root filesystem.  Specifying subdirectories in config files like we can do with rdiff-backup has no effect.  

Idea:  Write some code to keep track of these items:
- LVM snapshot base path (usually /tmp/label)
- List of subdirectories to back up, along with the associated full source path they belong in

Next, before we run rsync we check to see if the necessary folder tree is in place in the backup-store.  If not, we create it after stripping the LVM snapshot base path and building the tree from the source root filesystem down to the specified subdirectories (common case: mkdir /backup-store/label/home/username, then rsync to that directory).

**Comment by jpwoodbu** [comment]
I would think using the `--include` flag for rsync would yield the effect you're describing, albeit not as conveniently as using the `RDiffBackup.include()`.

Of course, given the age of this issue, it's likely obsolete anyway.
