### ISSUE TITLE
document better that a job config can override 'remote_user' setting

### ISSUE THREAD

**Issue by robled** [jpwoodbu/ari-backup#8]
Updated description to indicate that our docs either need to explain this better or at least include an example where the remote_user setting is being overridden.

original text:
Putting 'remote_user: root' in /etc/ari-backup/ari-backup.conf.yaml works well for Unixy systems, but not so well if you want to back up a Windows host along with your other systems.  You can work around this issue by creating a new Windows account named 'root', but some might find it preferable to use the built-in Administrator account for running backups.

**Comment by jpwoodbu** [comment]
The documentation has been updated to explain the relationship between settings, flags, and attributes in commit a95aa84b3ac695b8b50fdc3c8e367a0572c25347.
